{% set name = "sdaxen_python_utilities" %}
{% set version = "0.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sdaxen_python_utilities-{{ version }}.tar.gz
  sha256: 1c91a57766dc059b1400cc4f8c4555d351326d2582309e216bc62b3e541acfcd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - python_utilities
    - python_utilities.plotting
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sdaxen/python_utilities
  summary: A collection of useful tools for common Python tasks
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
    - sethaxen
